org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.112
neo_version_range=[26.1.2.21-beta,)

mod_id=appliedthaumics
mod_name=Applied Thaumics
mod_license=MIT
mod_version=1.0.7-Alpha
mod_group_id=com.traverse.appliedthaumics
mod_authors=Traverse_Joe
mod_description=A bridge between Thaumaturge and Applied Energistics 2. A Succesor of Thaumic Energistics.

jei_version=29.43.0.105
